name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    strategy:
      matrix:
        #  Node Version
        version: [18]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Build 🔧 
        run: |
          hugo --minify

      - name: Add CNAME File
        run: |
          cp -rf CNAME ./public

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
